version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U Ira -d postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  web:
    build: .
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/books
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "8000:8000"

  test:
    build: .
    command: sh -c "python manage.py migrate && python manage.py test books"
    volumes:
      - .:/books
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "5433:5432"

volumes:
  postgres_data:
